---
hostname: s1
ip_manage: 172.30.0.1
ssh_port: 22
username: openflow
password: openflow
device_type: linux


INTERFACES:
    - name: inside
      addr: 10.0.0.1/8
      description: InterfaceInterna
    - name: outside
      addr: 200.19.0.1/24
      description: InterfaceExterna