---
hostname: iptables-firewall
ip_manage: 127.0.0.1 
ssh_port: 22
username: admin
password: admin
device_type: linux


INTERFACES:
    - name: eth0
      addr: 10.0.0.1/8
      description: InterfaceInterna
    - name: eth1
      addr: 200.19.0.1/24
      description: InterfaceExterna
