---
hostname: cisco-firewall
ip_manage: 172.30.0.2
ssh_port: 22
username: cisco
password: cisco
device_type: cisco_ios

INTERFACES:
    - name: inside
      addr: 10.0.0.1/8
      description: InterfaceInterna
    - name: outside
      addr: 200.19.0.1/24
      description: InterfaceExterna